# Overrides for helm/app/values.yaml in the dev environment.
image:
  repository: 921876749389.dkr.ecr.eu-central-1.amazonaws.com/gitops-platform/app
  tag: 6ccb2bbc41eecef41e757712cff70e0c5c637664 # immutable git SHA

autoscaling:
  enabled: true # needs metrics-server

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
